FROM node:18.15.0-alpine3.17 as build

RUN mkdir /app

COPY . /app

WORKDIR /app

RUN yarn config set registry https://registry.npmmirror.com && \
    yarn install && \
    yarn build && \
    tar zcf build.tar.gz ./build

FROM nginx:1.18.0 as release

RUN mkdir /app

COPY --from=build /app/build.tar.gz /app

RUN tar zxf /app/build.tar.gz -C /app

COPY ./w8t.conf /etc/nginx/conf.d

WORKDIR /etc/nginx/

EXPOSE 80

CMD ["nginx","-g","daemon off;"]
